[[LLVMBootstrap_Clang]]
arch = "x86_64"
git-tree-sha1 = "724c3a6cab69536c2ba19490c2e8ab39734455d5"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "398056c22c5d96639dc6257f66a8ccae73910784b1f56d1bf5a91bbf82cce997"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "cba22bddfda326e7c6c7d930ad4ab31341b2cdb6"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "6c3e0b855e5ae95f9f476f6cc5b549b1abce482beeee80b2aee76b9ed5fa43c8"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-build_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a907e602478451e84eb60189ee17ed4f67a0d857"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "fdfc8f5122e19123bca736ad8684942a1afa6c0121eecbb289df3a6f6aac0b68"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-extract_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
