[[LLVMBootstrap_Clang]]
arch = "x86_64"
git-tree-sha1 = "724c3a6cab69536c2ba19490c2e8ab39734455d5"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "fa0cf64a79bc75ce28e73ee56ec703cbac8e107e5b9893419ce638f198250ccb"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "dd84c284c548fb04251973da50b5dcac55e7f73a"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "f9859fd2c46b93d1c0132a2aaa309362cd0989f6b0ab9921a2e53c7ef5d68303"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-build_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "db65c9b66033aac6eb7e9afa15b0c1ff8f2294ef"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "c87928f16458068831e3bb4ad6d9e0cf37c360dc9f6ff8bc0edba6120bb20bf8"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-extract_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
