[[LLVMBootstrap_Clang]]
arch = "x86_64"
git-tree-sha1 = "9a27511502613cbf73f50933476eb279f0cadbe1"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "36b33c2242517a5cc0ccaf373bd709b5a8880cbb1b90a9985fee16c9f5aab030"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[LLVMBootstrap_Clang]]
arch = "aarch64"
git-tree-sha1 = "d44370cfe4f570a511c0186fb20cd23e9e1ed1f6"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "0b47af1251ab3629c862c68c4b3881d6e90aee1bae6d28cc1a1bd0cb386b4d00"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "84718b2a977cf8114ed8b106c725297f5684ce96"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "997d463e8d26e4662f2f7e83d4f91e8664578aa33aeb060684ec2227fd24ab1e"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-build_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[LLVMBootstrap_Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "40b5e298aebabb2cee90af3eeb5d52cd3452f031"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "16adf7656dc0ce5ad0409323bc8f1531505f80496358c41e2fb099d7bf9be983"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-build_log-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "246fb2d394432f984fdbccd0a041850a3cb8a18c"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "579c84e69c11f2a380572e74ce0adb152037a632d4e3105c799e8bacd0ddd43c"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-extract_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[LLVMBootstrap_Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "ba13fdf925fc7d756cd93a514300323afd75ff5a"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "a0b98ed4b9e4ec534bcfc41e8ecabefa70dd97ac47bd6d415b5ceda34ac13339"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-extract_log-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"
