[[LLVMBootstrap_Clang]]
arch = "x86_64"
git-tree-sha1 = "724c3a6cab69536c2ba19490c2e8ab39734455d5"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "696695af6a0bf44db756fe5375bc47b6737344e99f8ca6915d7d59e5c226248a"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "64d7cd0cb92a857728386f9aaa1a3b248af2f2bc"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "4ff101cca3c74501b374bc0e9b66fe8cfdea7aaa6a84b683bc2f38cc6a148c20"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-build_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ffc25dcdbebd89026422f50f26b17de0c80fb072"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "2b4d1ccf932f74bc53be0465d9da3ced8a2bb5d4054e4e3199275ca3655e5198"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0-GCCBootstrap-x86_64-linux-gnu/LLVMBootstrap_Clang-extract_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
