[[LLVMBootstrap_Clang]]
arch = "x86_64"
git-tree-sha1 = "9130563b509a06c6db7f7289e8c5e7e51cbdcbf7"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "595742ab52de5e71b552a80c379bb5853b5bf2a122e9f786225e68fb83366624"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[LLVMBootstrap_Clang]]
arch = "aarch64"
git-tree-sha1 = "147da13022d82d2b3822f1f6f85acc32f03e16cc"
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang.download]]
    sha256 = "0dd86e24911c22d7a9561abff16f14d039b6af76ee28918ecc0a92ea990c8ead"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-build_log]]
arch = "x86_64"
git-tree-sha1 = "4660effde31602c76ef74b0524f01e76cd7e54f0"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "d90fb23cdda1284694d2bfb7925e4ab0d1c2e94878d79a9f7a900693b371b3d1"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-build_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[LLVMBootstrap_Clang-build_log]]
arch = "aarch64"
git-tree-sha1 = "b19f68af2fa4d6d30422f6713e38677e69790897"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-build_log.download]]
    sha256 = "2da4cae8701214472c7f9ab34f6bced4d8372bb8ab3b65bfb4edddd150de8eab"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-build_log-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"

[[LLVMBootstrap_Clang-extract_log]]
arch = "x86_64"
git-tree-sha1 = "955a968db70e677aac18abb54c347e5d7bc989d9"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "1aa89e45875b47e439064d0501c7d3d0175cfdb86b4085ada843551db5f5ca63"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-extract_log-v17.0.0-x86_64-linux-gnu-target+any.tar.gz"
[[LLVMBootstrap_Clang-extract_log]]
arch = "aarch64"
git-tree-sha1 = "eae8d8809b8831b38548d89bb45c92b7d0d2746e"
lazy = true
libc = "glibc"
os = "linux"
target = "any"

    [[LLVMBootstrap_Clang-extract_log.download]]
    sha256 = "721e3913422d0d3a70fb065e11e1869fd0972781a2face8bd78e28071938ead0"
    url = "https://github.com/staticfloat/LLVMBootstrap_Clang_jll.jl/releases/download/v17.0.0/LLVMBootstrap_Clang-extract_log-v17.0.0-aarch64-linux-gnu-target+any.tar.gz"
